# Generated by Django 4.1 on 2023-01-31 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('capital', models.CharField(max_length=100, verbose_name='Capital')),
                ('continent', models.CharField(blank=True, max_length=100, null=True, verbose_name='Continent')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Region')),
                ('largest_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Largest city')),
                ('area', models.IntegerField(blank=True, null=True, verbose_name='Area')),
                ('population', models.IntegerField(blank=True, null=True, verbose_name='Population')),
                ('density', models.FloatField(blank=True, null=True, verbose_name='Density')),
                ('gross_product', models.IntegerField(blank=True, null=True, verbose_name='Gross product')),
                ('currency', models.CharField(blank=True, max_length=50, null=True, verbose_name='Currency')),
                ('calling_code', models.IntegerField(blank=True, null=True, verbose_name='Calling code')),
            ],
        ),
    ]
