# Generated by Django 4.1 on 2023-02-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='demonym',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Demonym'),
        ),
        migrations.AddField(
            model_name='country',
            name='domain',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Top-level domain'),
        ),
        migrations.AddField(
            model_name='country',
            name='flag',
            field=models.ImageField(blank=True, null=True, upload_to='flags', verbose_name='Flag'),
        ),
        migrations.AddField(
            model_name='country',
            name='per_capita',
            field=models.IntegerField(blank=True, null=True, verbose_name='Per capita'),
        ),
    ]
